
name: ⚓ Build Pyinstaller

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: true
      matrix:
        # platform: [ubuntu-latest, windows-latest, macos-latest]
        platform: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      
      # - name: Install UPX
      #   uses: samyfodil/upx-action@v1.0.3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: |
          pip install pyinstaller

      - shell: bash
        run: |
          which pip
          which python
          which pyinstaller
          make build
          ls -lh bin
          cd bin
          tar -czvf pip-${{ matrix.platform }}.tar.gz pip


      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: pip-${{ matrix.platform }}
          path: |
            bin/*.tar.gz